# This is a basic workflow to help you get started with Actions

name: Testing lab3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
    - 'lab3/**'
    - '.github/workflows/lab3.yml'
    branches: [main]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      # Runs a set of commands using the runners shell
      - name: Run doctest
        run: |
          python -m doctest -v lab3/sudoku.py
